name: simple_scroll
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  gesture_recorder:
    path: ../
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
